version: "3"

services:
  nuxt:
    build: ./nuxt
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    working_dir: /src
    restart: always
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./nuxt:/src:cached

volumes:
  db_data:
